name: Build and deploy Node.js project to Azure Function - TEST

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    uses: vestfoldfylke/shared/.github/workflows/deploy-az-app-service-node.yml@main
    with:
      azure_appname: 'vfkplzminelevelotestsj'
      azure_functionapp_package_path: '.'
    secrets:
      azure_publishprofile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_TEST }}
